package kuu.nagoya.featurewordlist.infra

import kuu.nagoya.featurewordlist.entity.Word
import kuu.nagoya.featurewordlist.entity.WordGroup
import kuu.nagoya.featurewordlist.usecase.WordListReadonlyRepository

internal class WordListReadonlyRepositoryImpl :
    WordListReadonlyRepository {
    override suspend fun loadWordGroup(): List<WordGroup> {
        return listOf(
            WordGroup(
                0,
                "あいうえお",
                listOf(
                    Word(
                        0,
                        "あ",
                        "a"
                    ),
                    Word(
                        1,
                        "い",
                        "i"
                    ),
                    Word(
                        2,
                        "う",
                        "u"
                    ), Word(
                        3,
                        "え",
                        "e"
                    ),
                    Word(
                        4,
                        "お",
                        "o"
                    )
                )
            ),
            WordGroup(
                0,
                "かきくけこ",
                listOf(
                    Word(
                        0,
                        "か",
                        "ka"
                    ),
                    Word(
                        1,
                        "き",
                        "ki"
                    ),
                    Word(
                        2,
                        "く",
                        "ku"
                    ), Word(
                        3,
                        "け",
                        "ke"
                    ),
                    Word(
                        4,
                        "こ",
                        "ko"
                    )
                )
            ),
            WordGroup(
                0,
                "さしすせそ",
                listOf(
                    Word(
                        0,
                        "さ",
                        "sa"
                    ),
                    Word(
                        1,
                        "し",
                        "shi"
                    ),
                    Word(
                        2,
                        "す",
                        "su"
                    ), Word(
                        3,
                        "せ",
                        "se"
                    ),
                    Word(
                        4,
                        "そ",
                        "so"
                    )
                )
            ),
            WordGroup(
                0,
                "たちつてと",
                listOf(
                    Word(
                        0,
                        "た",
                        "ta"
                    ),
                    Word(
                        1,
                        "ち",
                        "ti"
                    ),
                    Word(
                        2,
                        "つ",
                        "tsu"
                    ), Word(
                        3,
                        "て",
                        "te"
                    ),
                    Word(
                        4,
                        "と",
                        "to"
                    )
                )
            ),
            WordGroup(
                0,
                "なにぬねの",
                listOf(
                    Word(
                        0,
                        "な",
                        "na"
                    ),
                    Word(
                        1,
                        "に",
                        "ni"
                    ),
                    Word(
                        2,
                        "く",
                        "nu"
                    ), Word(
                        3,
                        "け",
                        "ne"
                    ),
                    Word(
                        4,
                        "こ",
                        "no"
                    )
                )
            ),
            WordGroup(
                0,
                "はひふへほ",
                listOf(
                    Word(
                        0,
                        "は",
                        "ha"
                    ),
                    Word(
                        1,
                        "ひ",
                        "hi"
                    ),
                    Word(
                        2,
                        "ふ",
                        "hu"
                    ), Word(
                        3,
                        "へ",
                        "he"
                    ),
                    Word(
                        4,
                        "ほ",
                        "ho"
                    )
                )
            ),
            WordGroup(
                0,
                "まみむめも",
                listOf(
                    Word(
                        0,
                        "ま",
                        "ma"
                    ),
                    Word(
                        1,
                        "み",
                        "mi"
                    ),
                    Word(
                        2,
                        "む",
                        "mu"
                    ), Word(
                        3,
                        "め",
                        "me"
                    ),
                    Word(
                        4,
                        "も",
                        "mo"
                    )
                )
            ),
            WordGroup(
                0,
                "やゆよ",
                listOf(
                    Word(
                        0,
                        "や",
                        "ya"
                    ),
                    Word(
                        1,
                        "ゆ",
                        "yu"
                    ),
                    Word(
                        2,
                        "よ",
                        "yo"
                    )
                )
            ),
            WordGroup(
                0,
                "らりるれろ",
                listOf(
                    Word(
                        0,
                        "ら",
                        "ra"
                    ),
                    Word(
                        1,
                        "り",
                        "ri"
                    ),
                    Word(
                        2,
                        "る",
                        "ru"
                    ), Word(
                        3,
                        "れ",
                        "re"
                    ),
                    Word(
                        4,
                        "ろ",
                        "ro"
                    )
                )
            ),
            WordGroup(
                0,
                "わをん",
                listOf(
                    Word(
                        0,
                        "わ",
                        "wa"
                    ),
                    Word(
                        1,
                        "を",
                        "wo"
                    ),
                    Word(
                        2,
                        "ん",
                        "n"
                    )
                )
            )
        )
    }
}