name: Android CI

on:
  pull_request:
    branches:

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Build
        run: sudo ./gradlew build
  android_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Test
        run: sudo ./gradlew test
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Lint
        run: sudo ./gradlew lint
  android_ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Lint
        run: sudo ./gradlew ktlintCheck
  android_danger_ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: install danger
        run: |
          gem install bundler
          bundle install
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck
      - name: run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger