name: Android CI

on: [push]

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Build
        run: sudo ./gradlew build
  android_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Test
        run: sudo ./gradlew test
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Android SDk and Gradle Wrapper
        run: sudo ./gradlew wrapper
      - name: change permission
        run: sudo chmod 777 -R ./
      - name: Android Gradlew Lint
        run: sudo ./gradlew lint